"""Game definitions: balance, stats, and protocol."""

from .game_balance import (
    COMBAT_SECONDS,
    DEFAULT_TICK_RATE,
    GAME_PATHS,
    GOLD_PER_KILL,
    MAP_WIDTH_TILES,
    PLAYER_A,
    PLAYER_B,
    PLAYER_LIVES,
    PREP_SECONDS,
    ROUND_ACK_TIMEOUT,
    START_GOLD,
    TILE_SIZE_PX,
    TOWER_STATS,
    UNIT_STATS,
    TowerStats,
    UnitStats,
    tile_to_pixel,
)
from .protocol import (
    PlayerID,
    RoundResultData,
    RoundStartData,
    SimTowerData,
    SimUnitData,
    SimulationData,
)

__all__ = [
    "COMBAT_SECONDS",
    "DEFAULT_TICK_RATE",
    "GAME_PATHS",
    "GOLD_PER_KILL",
    "MAP_WIDTH_TILES",
    "PLAYER_A",
    "PLAYER_B",
    "PLAYER_LIVES",
    "PREP_SECONDS",
    "ROUND_ACK_TIMEOUT",
    "START_GOLD",
    "TILE_SIZE_PX",
    "TOWER_STATS",
    "UNIT_STATS",
    "TowerStats",
    "UnitStats",
    "tile_to_pixel",
    "PlayerID",
    "RoundResultData",
    "RoundStartData",
    "SimTowerData",
    "SimUnitData",
    "SimulationData",
]

