# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from td_shared.protobuf import (
    game_pb2 as shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2,
)

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in shared/src/td_shared/protobuf/game_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class YourGameServiceStub:
    """Service defining server-authoritative RPCs used during the preparation phase."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuildTower = channel.unary_unary(
            "/td_shared.YourGameService/BuildTower",
            request_serializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.BuildTowerRequest.SerializeToString,
            response_deserializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.BuildTowerResponse.FromString,
            _registered_method=True,
        )
        self.SendUnits = channel.unary_unary(
            "/td_shared.YourGameService/SendUnits",
            request_serializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.SendUnitsRequest.SerializeToString,
            response_deserializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.SendUnitsResponse.FromString,
            _registered_method=True,
        )
        self.QueueForMatch = channel.unary_stream(
            "/td_shared.YourGameService/QueueForMatch",
            request_serializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.QueueRequest.SerializeToString,
            response_deserializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.MatchEvent.FromString,
            _registered_method=True,
        )
        self.RoundAck = channel.unary_unary(
            "/td_shared.YourGameService/RoundAck",
            request_serializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.RoundAckRequest.SerializeToString,
            response_deserializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.RoundAckResponse.FromString,
            _registered_method=True,
        )


class YourGameServiceServicer:
    """Service defining server-authoritative RPCs used during the preparation phase."""

    def BuildTower(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendUnits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def QueueForMatch(self, request, context):
        """Client queues for a match; server streams queue updates and match start"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RoundAck(self, request, context):
        """Client signals that it finished rendering the current round"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_YourGameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "BuildTower": grpc.unary_unary_rpc_method_handler(
            servicer.BuildTower,
            request_deserializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.BuildTowerRequest.FromString,
            response_serializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.BuildTowerResponse.SerializeToString,
        ),
        "SendUnits": grpc.unary_unary_rpc_method_handler(
            servicer.SendUnits,
            request_deserializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.SendUnitsRequest.FromString,
            response_serializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.SendUnitsResponse.SerializeToString,
        ),
        "QueueForMatch": grpc.unary_stream_rpc_method_handler(
            servicer.QueueForMatch,
            request_deserializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.QueueRequest.FromString,
            response_serializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.MatchEvent.SerializeToString,
        ),
        "RoundAck": grpc.unary_unary_rpc_method_handler(
            servicer.RoundAck,
            request_deserializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.RoundAckRequest.FromString,
            response_serializer=shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.RoundAckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "td_shared.YourGameService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "td_shared.YourGameService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class YourGameService:
    """Service defining server-authoritative RPCs used during the preparation phase."""

    @staticmethod
    def BuildTower(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/td_shared.YourGameService/BuildTower",
            shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.BuildTowerRequest.SerializeToString,
            shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.BuildTowerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SendUnits(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/td_shared.YourGameService/SendUnits",
            shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.SendUnitsRequest.SerializeToString,
            shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.SendUnitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def QueueForMatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/td_shared.YourGameService/QueueForMatch",
            shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.QueueRequest.SerializeToString,
            shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.MatchEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RoundAck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/td_shared.YourGameService/RoundAck",
            shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.RoundAckRequest.SerializeToString,
            shared_dot_src_dot_td__shared_dot_protobuf_dot_game__pb2.RoundAckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
